@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/641857c4d5c2fc6a36f1cf22
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/6418583bba9097a02a80fc16/641857c4d5c2fc6a36f1cf22
Accept: application/json
withCredentials: true

{}
